### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by mjackson** [tuckerconnelly/uranium#1]
Hey @tuckerconnelly, nice work here! This looks great.

I had a quick question about usage. In [the first example in the README](https://github.com/tuckerconnelly/uranium/blob/0346583c1fc38707efd5f0d715bb602a095644a7/README.md#uranium), the media query is shown as a property of the `styles` object, like this:

```js
const styles = {
  base: {
    height: 120,
  },

  '@media (min-width: 600px)': { // <--- this is styles['@media (min-width: 600px)']
    base: {
      height: 56,
    },
  },
}
```

However, in [the Usage section](https://github.com/tuckerconnelly/uranium/blob/0346583c1fc38707efd5f0d715bb602a095644a7/README.md#usage), you show the media query being a property of `styles.base`, like this:

```js
const styles = {
  base: {
    backgroundColor: 'red',

    '@media (min-width: 480px)': { // <--- this is styles.base['@media (min-width: 480px)']
      backgroundColor: 'blue',
    }
  },
}
```

So my question is: which one is it? Or do they both work?

My guess is that it's the 2nd one and that the 1st example is possibly an earlier version of the API. Ideally I'd *like* to be able to use the 1st one, just because it reads a little more like a real stylesheet, but I can totally understand how the 2nd would be more straightforward to implement, especially for server-side rendering.

Kudos again for the great work you're doing here :) 👍

**Comment by tuckerconnelly** [comment]
Ah thanks! Yeah it's the second one :) your guess was spot on
