### ISSUE TITLE
Could this be used with styled-components ?

### ISSUE THREAD

**Issue by tlvenn** [tuckerconnelly/uranium#2]
Hi,

Thanks for this great project !

I am wondering if uranium could be integrated with the react native bridge in styled-components to provide media queries transparently ? This would be awesome.
> https://github.com/styled-components/styled-components

**Comment by tuckerconnelly** [comment]
Wow, styled components looks great!

I flipped through their source and it looks like it would work. And saw this guy: https://github.com/styled-components/styled-components/pull/11

SO, it looks like it _should_ work? If you just wrap it like:

``` js
const StyledView = Uranium(styled.View`
  background-color: papayawhip;
  @media (min-width: 200px) {
    background-color: blue;
  }
`)
```

Give it a shot and let me know. I'm usually around reactiflux #need-help channel from 10am-11am EST if you have any questions or wanna screenhero :)

**Comment by tlvenn** [comment]
Thanks for the quick reply @tuckerconnelly. I will investigate further, I am kinda hoping we can hide the Uranium wrapper given styled.View is already a wrapper itself. Will talk with the guys from styled-components.
