### ISSUE TITLE
Get rid of lodash?

### ISSUE THREAD

**Issue by bali182** [tuckerconnelly/uranium#4]
Hello! This library looks great, I'm currently thinking about giving it a go. But then I spotted the dreaded lodash dependency... 😢 would you be open to a PR to remove it?

I have seen 3 usages:

* `merge` - `src/plugins/mergeArray.js`
* `omit` - `src/resolveStyles.js`
* `unionWith` - `src/animate.js` - seems to be unused

I have 2 solutions in mind:

1. Put an `utils.js` in somewhere, and handwrite `omit` and `merge`
2. Add a webpack friendlier version. I maintain one called [mini-dash](https://github.com/healthiers/mini-dash) exactly to keep the 1.2kb dependency for a few short method out of the codebase. Imports for that could be replaced by

`import omit from 'mini-dash/omit' `- https://github.com/healthiers/mini-dash/blob/master/omit/index.js
`import merge from 'mini-dash/merge'` - https://github.com/healthiers/mini-dash/blob/master/merge/index.js

Which would include 2x~25 lines of code, instead of all of lodash.

Then the syntax is a bit different, since I tried to keep it very simple:

```js
// In my omit keys are explicitly defined as an array of strings
const withoutKeyAndRef = omit(newProps, ['key', 'ref'])
// Assuming these are objects, I don't have an array version yet
// Also no mutation in mini-dash, so the initial {} can be omited
const merged = merge(mergedStyles, currentStyle)
```

3. Any other alternative ???

**Comment by tuckerconnelly** [comment]
Hey thanks for the issue :)

This is so the webpack build size will be low, yeah? I think if all imports are the actual files, like:

```js
import merge from 'lodash/merge'
```

the build size would be low right? Would just need to change that omit import then

**Comment by bali182** [comment]
Yes that is much better! But still, just look at the source of these! The `lodash.<lib>` npm modules have no dependencies + flat the internal ones so you can see what you are getting into when using them or the 'lodash/<lib>' imports:

https://github.com/lodash/lodash/blob/4.5.0-npm-packages/lodash.omit/index.js ~1500 lines
https://github.com/lodash/lodash/blob/4.6.0-npm-packages/lodash.merge/index.js ~2200 lines

These most likely share some common code, when you import them the way you do. But for 2 trivial methods do you really need 3700 lines of code? 😢

**Also I completely understand if you don't want a handwritten version of these or use an unknown lib**, so that's why I tried to formulate this more like a question. Feel free to close this, the `'lodash/<module>'` importing is a big improvement over the destructured import!

**Comment by bali182** [comment]
Also just a bit more convincing: https://github.com/Semantic-Org/Semantic-UI-React/issues/864 😉

**Comment by tuckerconnelly** [comment]
Yeah I think it makes a lot of sense to use mini-dash. Unfortunately there aren't any tests for Uranium yet, so I think I gotta do it myself and make sure the larger projects still work. I'll give it a shot today or at some point this week :)

**Comment by tuckerconnelly** [comment]
Hey @bali182 gave mini-dash a shot, and the performance was (unfortunately) noticeably slower. Fast merges are necessary 'cause Uranium calls `merge` and `React.createElement` quite rapidly and quite a lot.

Can you do some performance testing and comment here again?

In the meantime, I switched over to `lodash/*` form :)

Thanks again!

**Comment by bali182** [comment]
Wow, that's unexpected! I implemented `merge` (and the whole lib) in a very optimistic way, so will check out what lodash does differently! Thanks for pointing that out!
