### ISSUE TITLE
Warning in unit test using Jest

### ISSUE THREAD

**Issue by made-aryadinata** [tuckerconnelly/uranium#7]
When I test a component using Jest, the following warning appears:
```
global.matchMedia not found. Uranium has mocked it for you. To get rid of this warning, in your index.ios.js or index.android.js set global.matchMedia to react-native-match-media or to Uranium's `matchMediaMock`. See the Uranium docs for details.
```
Things I have tried, but not working:
- Set global.matchMedia in index.ios.js and index.android.js
- Set global.matchMedia in unit test's `beforeEach`

**Comment by tuckerconnelly** [comment]
Hey! Give this a read: http://stackoverflow.com/questions/39830580/jest-test-fails-typeerror-window-matchmedia-is-not-a-function

And then check out https://facebook.github.io/jest/docs/configuration.html#setuptestframeworkscriptfile-string for creating a setup file :) Should be able to throw a matchMedia mock in there.

**Comment by tuckerconnelly** [comment]
Feel free to re-open or hmu on the Twitter if you still have problems :)

**Comment by made-aryadinata** [comment]
Thanks for answering, it solved the problem 👍
